version: "3.8"

services:
  chat-service:
    build: .
    ports:
      - "3004:3004"
    env_file:
      - .env
    depends_on:
      - chat-mongo

  chat-mongo:
    image: mongo:6.0
    container_name: chat-mongo
    ports:
      - "27021:27017"
    volumes:
      - chat-mongo-data:/data/db

volumes:
  chat-mongo-data:
